#! /usr/local/bin/python3
#Author: Andrew Gerber-Duffy
import sys

if len(sys.argv) == 1:
    print("seq Usage: [start], stop[, step]")
    sys.exit(0)

if len(sys.argv) == 2:
    for i in range(1,int(sys.argv[1]) + 1):
        print(i)

elif len(sys.argv) == 3:
    for i in range(int(sys.argv[1]), int(sys.argv[2]) + 1):
        print(i)

else:
    if float(sys.argv[3]) % 1 == 0:
        for i in range(int(sys.argv[1]), int(sys.argv[2])+1, int(sys.argv[3])):
            print(i)

